// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY22mIsoUHHr2DTRg1DSg9i9i-pPNxpkU',
    appId: '1:674970951243:web:075e7c59700e794d0137ce',
    messagingSenderId: '674970951243',
    projectId: 'footlinker-feup',
    authDomain: 'footlinker-feup.firebaseapp.com',
    storageBucket: 'footlinker-feup.appspot.com',
    measurementId: 'G-58R537PBHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT2e1M9awhj6bg3uhn3F_mKhxbuW9NoT4',
    appId: '1:674970951243:android:b11fc1e832dbb6ae0137ce',
    messagingSenderId: '674970951243',
    projectId: 'footlinker-feup',
    storageBucket: 'footlinker-feup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnMS_fBl2ooA8RFGq1rKSJJ8wjThXu1P4',
    appId: '1:674970951243:ios:ac33535c90c183f50137ce',
    messagingSenderId: '674970951243',
    projectId: 'footlinker-feup',
    storageBucket: 'footlinker-feup.appspot.com',
    iosClientId:
        '674970951243-gpoiltmc4lfb2f6ej7p4t86u8quoc6mc.apps.googleusercontent.com',
    iosBundleId: 'pt.up.fe.footlinker.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnMS_fBl2ooA8RFGq1rKSJJ8wjThXu1P4',
    appId: '1:674970951243:ios:ac33535c90c183f50137ce',
    messagingSenderId: '674970951243',
    projectId: 'footlinker-feup',
    storageBucket: 'footlinker-feup.appspot.com',
    iosClientId:
        '674970951243-gpoiltmc4lfb2f6ej7p4t86u8quoc6mc.apps.googleusercontent.com',
    iosBundleId: 'pt.up.fe.footlinker.app',
  );
}
