name: Acceptance Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  drive_android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
          channel: 'stable'
      
      - name: Run Acceptance Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: playstore
          api-level: 29
          arch: x86_64
          profile: Nexus 6
          script: flutter driver --target=test_driver/app.dart
